POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "bc@miu.edu",
  "password": "bc123"
}

###
POST localhost:8080/api/users
Content-Type: application/json

{
  "name": "Bob Cameron",
  "email": "bc@miu.edu",
  "password": "bc123",
  "roles": ["SELLER"]
}

###
POST localhost:8080/api/products
Content-Type: application/json

{
  "name": "Learn Java",
  "description" : "Book that help you to learn Java",
  "startPrice" : 12.0,
  "bidDueDate" : "2023-08-08",
  "bidPaymentDueDate" : "2023-08-10",
  "categories": [{
    "name" : "Book"
  }],
  "release" : false
}

###
GET localhost:8080/api/users/2
Content-Type: application/json
Authorization: bear eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLGJjQG1pdS5lZHUiLCJpc3MiOiJBVSIsImlhdCI6MTY5ODEzMDY3NiwiZXhwIjoxNjk4MTM0Mjc2fQ.xQN0OoQ7uWa6ZixxEXlM_WoIGreo8-OkNpmywniZTuBCD7uomCwsoGDp7qdWyM7Q9oPPvMgZGZ-E-a6Mp1tj0g

###
GET localhost:8080/api/products?page=0&pageSize2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLGJjQG1pdS5lZHUiLCJpc3MiOiJBVSIsImlhdCI6MTY5ODEzMDY3NiwiZXhwIjoxNjk4MTM0Mjc2fQ.xQN0OoQ7uWa6ZixxEXlM_WoIGreo8-OkNpmywniZTuBCD7uomCwsoGDp7qdWyM7Q9oPPvMgZGZ-E-a6Mp1tj0g

###
POST localhost:8080/api/bidproduct
Content-Type: application/json

{
  "productId" : 4,
  "email": "bc@miu.edu",
  "deposit" : 600.0
}

###
GET localhost:8080/api/users/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLGpmQG1pdS5lZHUiLCJpc3MiOiJBVSIsImlhdCI6MTY5ODA5MTkwOCwiZXhwIjoxNjk4MDk1NTA4fQ.qTc7_nePjgRq2o4as-kqrskMZcdIj9gTbMYuaFeuAT0QyUDEm6_jrFkIbu-8QzkYK-MeqQX8x42zWlkRZSkYNg