POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Bob Cameron",
  "email": "bc@miu.edu",
  "password": "bc123",
  "roles": ["SELLER"]
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "bc@miu.edu",
  "password": "bc123"
}

###
GET http://localhost:8080/api/users/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLGJjQG1pdS5lZHUiLCJpc3MiOiJBVSIsImlhdCI6MTY5ODA4OTAyNywiZXhwIjoxNjk4MDkyNjI3fQ.Lb8dIY1nR9d6H01ClhwPGSIClgjYwJa1wLNq8T-2dYserTOEfILvSJH_-2hd0qWEvMusglzKgIGA6hh9XVOLug
Content-Type: application/json
